### PR TITLE
Initial "ETL" Script to Import EPJS Data into PostgreSQL

### PR DESCRIPTION
**Pull request by nelsonic**
For https://github.com/healthlocker/healthlocker/issues/122

### CODE REVIEW

**Comment by nkamc** [comment]
https://www.microsoft.com/en-GB/download/details.aspx?id=5783 "Compact Version" for Desktop

**Comment by nkamc** [comment]
http://dba.stackexchange.com/questions/20078/can-i-restore-a-sql-server-bak-files-without-sql-server

**Comment by intool** [comment]
00-download-sql
00-express-edition-also-doesnt-install
00-sql-wont-work-on-this-machine

**Comment by nelsonic** [comment]
We have decided to connect to MSSQL so this is no longer required

**Pull request merged**
